services:
  apache:
    build:
      context: ./apache
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - sock:/var/run/php-fpm
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./apache/conf.modules.d:/usr/local/apache2/conf.modules.d
      - ./apache/conf.d:/usr/local/apache2/conf.d
      - ./simgos-rpm/var/www/html:/var/www/html # mount web document root
      - ./alat:/var/www/html/alat
    depends_on:
      - php-fpm
    networks:
      - simgos-network
  php-fpm:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    volumes:
      - sock:/var/run/php-fpm
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./simgos-rpm/var/www/html:/var/www/html # mount web document root
      - ./php-fpm/local.php:/var/www/html/production/webapps/webservice/config/autoload/local.php
      - ./php-fpm/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini #debugging, uncomment untuk debugging, jangan lupa ubah IP pada file
      - ./reports:/var/www/html/production/webapps/webservice/reports # mount reports, uncomment jika menggunakan reports sendiri
      - ./alat:/var/www/html/alat # uncomment untuk tools tambahan
    networks:
      - simgos-network
    #cap_add:  #slowlog req
    #  - SYS_PTRACE #slowlog req
    #  - SYS_ADMIN #slowlog req
  tomcat:
    build:
      context: ./tomcat
      dockerfile: Dockerfile
    volumes:
      - ./simgos-rpm/var/www/html:/var/www/html
      - ./reports:/var/www/html/production/webapps/webservice/reports
    ports:
      - "8080:8080"
    networks:
      - simgos-network

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "S!MGos2R00T@kemkes.go.id" # boleh uncomment jika fresh install dan tidak install db
    ports:
      - "3306:3306"
    volumes:
      - sock:/sock
      - /mnt/d/Dev/simgos-dev-db:/var/lib/mysql
      #- /mnt/d/Dev/simgos-db:/var/lib/mysql #contoh mounting mysqldata ke D:\Dev\simgos-db pada Docker for windows
      #- /home/simgos/simgos-dev-db:/var/lib/mysql #contoh mount mysqldata ke /home/simgos/simgos-db / data pada wsl
    networks:
      - simgos-network
networks:
  simgos-network:
volumes:
  sock:
    driver: local
